site_name: We部 資料 置き場

nav:
  - はじめに: index.md
  - We部について: about.md
  - 年間スケジュール: schedule.md
  - よくある質問: faq.md
  - 活動報告:
    - テンプレート: activities/reports/template.md
  - 運営メモ: operations.md

theme:
  name: material
  language: ja
  font:
    text: Noto Sans JP
    code: Noto Sans Mono

repo_url: https://github.com/junhat6/web-community-vault
edit_uri: '#root/path/docs/'

extra:
  search:
    language: 'jp'

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          