site_name: We部 資料 置き場
site_url: https://junhat6.github.io/web-community-vault/

repo_url: https://github.com/junhat6/web-community-vault

nav:
  - はじめに: index.md
  - We部について: about.md
  - 年間スケジュール: schedule.md
  - よくある質問: faq.md
  - 運営メモ: operations.md
  - 活動記録:
    - blog/index.md

theme:
  name: material
  language: ja
  font:
    text: Noto Sans JP
    code: Noto Sans Mono

plugins:
  - blog
  - search:
      lang: ja
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          