name: Sync Google Drive
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Combine md files into single txt
      run: |
        find docs -name "*.md" | sort | xargs cat > $GITHUB_WORKSPACE/combined-docs.txt
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: copy /github/workspace/combined-docs.txt gdrive:/web-community-vault